[tool.poetry]
name = "ledger-report"
version = "0.1.0"
description = ""
authors = ["Christian <c.ship.johnson@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyqt6 = "6.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
