[tool.poetry]
name = "ledger-report"
version = "0.1.0"
description = ""
authors = ["Christian <c.ship.johnson@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ledger-cli = "^0.1.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
